service:
  port: 8080
  # If the following are uncommented, then the server will operate over TLS
  tlsCertificate: /usr/src/server.crt
  tlsPrivateKey: /usr/src/server.key

metrics:
  port: 2112
  endpoint: "/metrics"
